apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-h8c5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-h8c5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-h8c5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-h8c5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-h8c5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hiup-tenant/rhtap-demo-app/hacbs-test-project-h8c5@sha256:e9790fc77986ddb388b7156e5f8946091e899b69050d03ec403ed0d434b84cb7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
